# SPDX-License-Identifier: GPL-3.0-or-later

name := discordrp

pnpm ?= pnpm
pnpm += install
pnpm-d := $(pnpm) -D

m4 ?= m4
m4 := printf 'changequote([[, ]])' | $(m4) -

esbuild ?= esbuild
esbuild += --bundle --format=esm
esbuild += --define:NULL=null --define:NAME='"$(name)"'

terser ?= terser
terser += --module --ecma 2020 --mangle --comments false \
	  --compress 'passes=3,pure_getters=true,unsafe=true'

prefix := build
m4-prefix := $(prefix)/m4
modules-prefix := node_modules
icomap-prefix := material-icon/src/core/icons

gen-icomap := scripts/gen-icomap.ts

ifneq ($(minimize),)
	minimize := -terser
endif

ifneq ($(debug),)
	debug := -debug
endif

.PHONY: install uninstall publish
install:

package := package.json
package-conf := $(package).in $(wildcard package/*.json)

npm-modules := escape-string-regexp
npm-modules := $(addprefix $(modules-prefix)/,$(npm-modules))
npm-modules := $(addsuffix /$(package),$(npm-modules))

$(modules-prefix)/%/$(package):
	$(pnpm-d) $*
	touch $(firstword $(package-conf))

$(package): $(package-conf) $(npm-modules)
	$(m4) $< >$@

discordrp-m4 := entry.js $(wildcard cmd/*.js) $(wildcard lib/*.js)
discordrp-m4 := $(addprefix $(m4-prefix)/,$(discordrp-m4))
discordrp := $(prefix)/entry.js
m4lib := $(wildcard lib/*.m4)

$(m4-prefix)/%: % $(m4lib)
	mkdir -p $(@D)
	$(m4) $(m4lib) $< >$@


icomap := $(prefix)/icomap.js

$(icomap)on: $(icomap-prefix)/fileIcons.ts $(icomap-prefix)/languageIcons.ts
	$(gen-icomap) >$@

$(icomap): $(icomap)on
	printf '/* Generated by %s and %s */\n\n' $(gen-icomap) \
	       $(lastword $(MAKEFILE_LIST)) >$@
	printf 'const icomap = ' >>$@
	cat $(icomap)on >>$@

$(discordrp)1: $(discordrp-m4) $(package) $(icomap)
	$(esbuild) --banner:js="import { createRequire } from 'node:module'; \
		   		var require = createRequire(import.meta.url);" \
		   --sourcemap --platform=node --external:vscode --outfile=$@ $<

discordrp-terser := $(addsuffix 1-terser,$(discordrp))
discordrp-debug  := $(addsuffix -debug,$(discordrp))

$(discordrp-terser): %1-terser: %1
	$(terser) <$< >$@

$(discordrp-debug): %-debug: %1
	ln -f $< $@
	ln -f $< $*

$(discordrp): %: %1$(minimize)
	head -n1 entry.js >$@
	printf '\n' >>$@
	cat $< >>$@

images  := $(wildcard images/*)
archive := $(prefix)/$(name).vsix

$(archive): README.md $(discordrp)$(debug) $(images)
	vsce package --skip-license -o $@

install: $(archive)
	code --install-extension $<

uninstall:
	code --uninstall-extension \
	     $$(code --list-extensions | grep $(name) || printf '39\n')

publish: $(archive)
	vsce publish --skip-license

.PHONY: clean distclean

clean:
	rm -f $(archive) $(discordrp-m4) $(icomap)* $(discordrp)*

distclean: clean
	test -d $(modules-prefix) && \
	find $(modules-prefix) -mindepth 1 -maxdepth 1 -exec rm -rf {} +
