# SPDX-License-Identifier: GPL-3.0-or-later

name := discordrp

m4 ?= m4
m4 := printf 'changequote([[, ]])' | $(m4) -

esbuild ?= esbuild
esbuild += --bundle --format=esm --platform=node
esbuild += --define:NULL=null --define:NAME='"$(name)"'

terser ?= terser
terser += --module --ecma 2020 --mangle --comments false \
	  --compress 'passes=3,pure_getters=true,unsafe=true'

prefix := build
m4-prefix := $(prefix)/m4
icomap-prefix := material-icon/src/core/icons

gen-cmdlist := scripts/gen-cmdlist.sh
gen-icomap  := scripts/gen-icomap.ts

ifneq ($(minimize),)
	minimize := -terser
endif

.PHONY: install uninstall publish
install:

package := package.json
package-conf := $(package).in $(wildcard package/*.json)
cmdef := lib/cmd.m4

$(package): $(package-conf) $(cmdef)
	$(m4) $(cmdef) $< >$@

cmds := $(wildcard cmd/*)
cmdlist := $(m4-prefix)/cmdlist.js

cmdlist.js: $(cmds) $(cmdef)
	ls cmd/* | $(gen-cmdlist) >$@

discordrp-m4 := entry.js $(wildcard cmd/*.js) $(wildcard lib/*.js)
discordrp-m4 := $(addprefix $(m4-prefix)/,$(discordrp-m4))
discordrp := $(prefix)/entry.js
m4lib := $(wildcard lib/*.m4)

$(cmdlist): cmdlist.js

$(m4-prefix)/%: $(m4lib) %
	mkdir -p $(@D)
	$(m4) $^ >$@

icomap := $(m4-prefix)/icomap.js

$(icomap)on: $(icomap-prefix)/fileIcons.ts $(icomap-prefix)/languageIcons.ts
	$(gen-icomap) >$@

$(icomap): $(icomap)on
	printf '/* Generated by %s and %s */\n\n' $(gen-icomap) \
	       $(lastword $(MAKEFILE_LIST)) >$@
	printf 'export default ' >>$@
	cat $(icomap)on >>$@

$(discordrp)1: $(discordrp-m4) $(package) $(icomap) $(cmdlist)
	$(esbuild) --banner:js="import { createRequire } from 'node:module'; \
		   		var require = createRequire(import.meta.url);" \
		   --sourcemap=inline --external:vscode --outfile=$@ $<

discordrp-terser := $(addsuffix 1-terser,$(discordrp))

$(discordrp-terser): %1-terser: %1
	$(terser) <$< >$@

$(discordrp): %: %1$(minimize)
	head -n1 entry.js >$@
	printf '\n' >>$@
	cat $< >>$@

images  := $(wildcard images/*)
archive := $(prefix)/$(name).vsix

$(archive): README.md $(discordrp) $(images)
	vsce package --skip-license -o $@

install: $(archive)
	code --install-extension $<

uninstall:
	code --uninstall-extension \
	     $$(code --list-extensions | grep $(name) || printf '39\n')

publish: $(archive)
	vsce publish --skip-license

.PHONY: clean distclean

clean:
	rm -f $(archive) $(discordrp-m4) $(icomap)* $(discordrp)* $(cmdlist)

distclean: clean
	rm -f $(package) cmdlist.js README.md
