#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

printf '/* Generated by %s */\n\n' $0
printf 'export default [\n'

while read file; do
	name=$(basename $file | cut -d. -f1 | tr [[:lower:]] [[:upper:]])

	printf "\t[ 'CMD_%s', import('./%s') ],\n" $name $file
done

printf ']\n'
